debug: true
spring:
  task:
    scheduling:
      pool:
        size: 10
    execution:
      pool:
        queue-capacity: 100
        core-size: 10
        max-size: 15
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db_mail:5432/fitness
    username: fitness
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: final.project.jd2@gmail.com
    password: fszwvixrggbafile
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
