server:
  port: 8092
debug: true
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://db_audit:5432/fitness
    #username: fitness
    #password: root
    url: jdbc:postgresql://localhost:5432/final_project
    username: postgres
    password: qaz741
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
jwt:
  secret: zgxdtyjuihlhi
  issuer: fitnessStudio