debug: true
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db_user:5432/fitness
    username: fitness
    password: root
  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
jwt:
  secret: zgxdtyjuihlhi
  issuer: fitnessStudio
audit:
  url: http://audit-service:8080/audit/inner
mail:
  url: http://mail-service:8080/mails
