debug: true
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/micro
    username: micro
    password: root
jwt:
  secret: zgxdtyjuihlhi
  issuer: fitnessStudio
